do
$$
declare
     i int;
begin
for  i in 1..30
loop
    insert into "public"."sessions" ("user_id", "clock_in", "clock_out", "was_scheduled")
    values
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'02 day' + interval'21 hours')::timestamp, (now()::date - interval'01 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'03 day' + interval'21 hours')::timestamp, (now()::date - interval'02 day' + interval'1.5 hours')::timestamp, false),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'04 day' + interval'21 hours')::timestamp, (now()::date - interval'03 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'05 day' + interval'21 hours')::timestamp, (now()::date - interval'04 day' + interval'1.5 hours')::timestamp, false),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'06 day' + interval'21 hours')::timestamp, (now()::date - interval'05 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'07 day' + interval'21 hours')::timestamp, (now()::date - interval'06 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'08 day' + interval'21 hours')::timestamp, (now()::date - interval'07 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'09 day' + interval'21 hours')::timestamp, (now()::date - interval'08 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'10 day' + interval'21 hours')::timestamp, (now()::date - interval'09 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'11 day' + interval'21 hours')::timestamp, (now()::date - interval'10 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'12 day' + interval'21 hours')::timestamp, (now()::date - interval'11 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'13 day' + interval'21 hours')::timestamp, (now()::date - interval'12 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'14 day' + interval'21 hours')::timestamp, (now()::date - interval'13 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'15 day' + interval'21 hours')::timestamp, (now()::date - interval'14 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'16 day' + interval'21 hours')::timestamp, (now()::date - interval'15 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'17 day' + interval'21 hours')::timestamp, (now()::date - interval'16 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'18 day' + interval'21 hours')::timestamp, (now()::date - interval'17 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'19 day' + interval'21 hours')::timestamp, (now()::date - interval'18 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'20 day' + interval'21 hours')::timestamp, (now()::date - interval'19 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'21 day' + interval'21 hours')::timestamp, (now()::date - interval'20 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'22 day' + interval'21 hours')::timestamp, (now()::date - interval'21 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'23 day' + interval'21 hours')::timestamp, (now()::date - interval'22 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'24 day' + interval'21 hours')::timestamp, (now()::date - interval'23 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'25 day' + interval'21 hours')::timestamp, (now()::date - interval'24 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'26 day' + interval'21 hours')::timestamp, (now()::date - interval'25 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'27 day' + interval'21 hours')::timestamp, (now()::date - interval'26 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'28 day' + interval'21 hours')::timestamp, (now()::date - interval'27 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'29 day' + interval'21 hours')::timestamp, (now()::date - interval'28 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'30 day' + interval'21 hours')::timestamp, (now()::date - interval'29 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'31 day' + interval'21 hours')::timestamp, (now()::date - interval'30 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'32 day' + interval'21 hours')::timestamp, (now()::date - interval'31 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'33 day' + interval'21 hours')::timestamp, (now()::date - interval'32 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'34 day' + interval'21 hours')::timestamp, (now()::date - interval'33 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'35 day' + interval'21 hours')::timestamp, (now()::date - interval'34 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'36 day' + interval'21 hours')::timestamp, (now()::date - interval'35 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'37 day' + interval'21 hours')::timestamp, (now()::date - interval'36 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'38 day' + interval'21 hours')::timestamp, (now()::date - interval'37 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'39 day' + interval'21 hours')::timestamp, (now()::date - interval'38 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'40 day' + interval'21 hours')::timestamp, (now()::date - interval'39 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'41 day' + interval'21 hours')::timestamp, (now()::date - interval'40 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'42 day' + interval'21 hours')::timestamp, (now()::date - interval'41 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'43 day' + interval'21 hours')::timestamp, (now()::date - interval'42 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'44 day' + interval'21 hours')::timestamp, (now()::date - interval'43 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'45 day' + interval'21 hours')::timestamp, (now()::date - interval'44 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'46 day' + interval'21 hours')::timestamp, (now()::date - interval'45 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'47 day' + interval'21 hours')::timestamp, (now()::date - interval'46 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'48 day' + interval'21 hours')::timestamp, (now()::date - interval'47 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'49 day' + interval'21 hours')::timestamp, (now()::date - interval'48 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'50 day' + interval'21 hours')::timestamp, (now()::date - interval'49 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'51 day' + interval'21 hours')::timestamp, (now()::date - interval'50 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'52 day' + interval'21 hours')::timestamp, (now()::date - interval'51 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'53 day' + interval'21 hours')::timestamp, (now()::date - interval'52 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'54 day' + interval'21 hours')::timestamp, (now()::date - interval'53 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'55 day' + interval'21 hours')::timestamp, (now()::date - interval'54 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'56 day' + interval'21 hours')::timestamp, (now()::date - interval'55 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'57 day' + interval'21 hours')::timestamp, (now()::date - interval'56 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'58 day' + interval'21 hours')::timestamp, (now()::date - interval'57 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'59 day' + interval'21 hours')::timestamp, (now()::date - interval'58 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'60 day' + interval'21 hours')::timestamp, (now()::date - interval'59 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'61 day' + interval'21 hours')::timestamp, (now()::date - interval'60 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'62 day' + interval'21 hours')::timestamp, (now()::date - interval'61 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'63 day' + interval'21 hours')::timestamp, (now()::date - interval'62 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'64 day' + interval'21 hours')::timestamp, (now()::date - interval'63 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'65 day' + interval'21 hours')::timestamp, (now()::date - interval'64 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'66 day' + interval'21 hours')::timestamp, (now()::date - interval'65 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'67 day' + interval'21 hours')::timestamp, (now()::date - interval'66 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'68 day' + interval'21 hours')::timestamp, (now()::date - interval'67 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'69 day' + interval'21 hours')::timestamp, (now()::date - interval'68 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'70 day' + interval'21 hours')::timestamp, (now()::date - interval'69 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'71 day' + interval'21 hours')::timestamp, (now()::date - interval'70 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'72 day' + interval'21 hours')::timestamp, (now()::date - interval'71 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'73 day' + interval'21 hours')::timestamp, (now()::date - interval'72 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'74 day' + interval'21 hours')::timestamp, (now()::date - interval'73 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'75 day' + interval'21 hours')::timestamp, (now()::date - interval'74 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'76 day' + interval'21 hours')::timestamp, (now()::date - interval'75 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'77 day' + interval'21 hours')::timestamp, (now()::date - interval'76 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'78 day' + interval'21 hours')::timestamp, (now()::date - interval'77 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'79 day' + interval'21 hours')::timestamp, (now()::date - interval'78 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'80 day' + interval'21 hours')::timestamp, (now()::date - interval'79 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'81 day' + interval'21 hours')::timestamp, (now()::date - interval'80 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'82 day' + interval'21 hours')::timestamp, (now()::date - interval'81 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'83 day' + interval'21 hours')::timestamp, (now()::date - interval'82 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'84 day' + interval'21 hours')::timestamp, (now()::date - interval'83 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'85 day' + interval'21 hours')::timestamp, (now()::date - interval'84 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'86 day' + interval'21 hours')::timestamp, (now()::date - interval'85 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'87 day' + interval'21 hours')::timestamp, (now()::date - interval'86 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'88 day' + interval'21 hours')::timestamp, (now()::date - interval'87 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'89 day' + interval'21 hours')::timestamp, (now()::date - interval'88 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'90 day' + interval'21 hours')::timestamp, (now()::date - interval'89 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'91 day' + interval'21 hours')::timestamp, (now()::date - interval'90 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'92 day' + interval'21 hours')::timestamp, (now()::date - interval'91 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'93 day' + interval'21 hours')::timestamp, (now()::date - interval'92 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'94 day' + interval'21 hours')::timestamp, (now()::date - interval'93 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'95 day' + interval'21 hours')::timestamp, (now()::date - interval'94 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'96 day' + interval'21 hours')::timestamp, (now()::date - interval'95 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'97 day' + interval'21 hours')::timestamp, (now()::date - interval'96 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'98 day' + interval'21 hours')::timestamp, (now()::date - interval'97 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'99 day' + interval'21 hours')::timestamp, (now()::date - interval'98 day' + interval'1.5 hours')::timestamp, true),
    (lpad(i::text, 32, '0')::uuid, (now()::date - interval'100 day' + interval'21 hours')::timestamp, (now()::date - interval'99 day' + interval'1.5 hours')::timestamp, true);
end loop;
end;
$$;

alter sequence "public"."sessions_id_seq" start with 10000;
alter sequence "public"."sessions_id_seq" restart;
